stages:
  - node_build
  - docker_build

node_build:
  stage: node_build
  only:
    - tags
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - ls
  tags:
    - shell
  artifacts:
    paths:
      - dist/

docker_build:
  stage: docker_build
  only:
    - tags
  dependencies:
    - node_build
  script:
    - BUILD_TAG=$CI_COMMIT_TAG
    - docker version
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-beijing.aliyuncs.com
    - ls
    - docker build -t cms-template:$BUILD_TAG .
    - IMAGE_ID=$(docker images | grep cms-template | grep $BUILD_TAG | awk '{print $3}')
    - docker tag $IMAGE_ID registry.cn-beijing.aliyuncs.com/aimer-fan/cms-template:$BUILD_TAG
    - docker push registry.cn-beijing.aliyuncs.com/aimer-fan/cms-template:$BUILD_TAG
    - docker rmi -f $IMAGE_ID
  tags:
    - shell
